// Builds manual/index.html from the page modules. Run: npm --prefix brand run build
import { writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(root, "manual/pages");
const modules = readdirSync(dir).filter((f) => f.endsWith(".mjs")).sort();
const pages = [];
for (const file of modules) pages.push(...(await import(path.join(dir, file))).default);

let html = pages.map((p, i) => p(i + 1)).join("\n");
// Fill the contents page with the first page number of each chapter.
const first = {};
let n = 0;
html.replace(/data-chapter="(\d*)"/g, (m, ch) => { n++; if (ch && !(ch in first)) first[ch] = n; return m; });
html = html.replace(/data-toc="(\d\d)"><\/span>/g, (m, ch) => `data-toc="${ch}">${String(first[ch] ?? "").padStart(2, "0")}</span>`);

const doc = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=1600">
<title>Wuu 品牌手册 · Brand guidelines</title>
<!-- Generated by brand/src/build-manual.mjs from brand/src/manual/pages. Edit the sources, then run npm --prefix brand run build. -->
<link rel="stylesheet" href="manual.css">
<script src="../assets/motion/wuu-ball.js"></script>
</head>
<body>
<main class="book">
${html}
</main>
<script>
// Live motion specimens; PDF export shows their first frame.
document.querySelectorAll("[data-wuu-live]").forEach(function (el) {
  var states = el.dataset.wuuLive.split(","), i = 0;
  var ball = WuuBall.mount(el, { px: +el.dataset.px || 96, body: el.dataset.body, eye: el.dataset.eye, state: states[0], reducedMotion: el.dataset.reduced === "1" ? true : undefined });
  if (states.length > 1) setInterval(function () { i = (i + 1) % states.length; ball.set(states[i]); }, +el.dataset.every || 2200);
});
</script>
</body>
</html>
`;
writeFileSync(path.join(root, "../manual/index.html"), doc);
console.log(`manual/index.html: ${pages.length} pages`);
