import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const root = path.resolve(process.argv[2] || 'desktop/out/e2e/annotation-comparison');
const output = path.join(root, 'comparison');
fs.mkdirSync(output, { recursive: true });
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const run = args => {
  const result = spawnSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...args], { encoding: 'utf8' });
  if (result.status !== 0) throw new Error(result.stderr || `ffmpeg exited ${result.status}`);
};
const manifests = Object.fromEntries(['baseline', 'refined'].map(variant => [variant,
  read(path.join(root, variant, 'annotation-comparison', 'manifest.json'))]));
const results = Object.fromEntries(['baseline', 'refined'].map(variant => [variant,
  read(path.join(root, variant, 'results.json'))]));
assert.equal(manifests.baseline.originalSHA, manifests.refined.originalSHA, 'Both builds must use identical PDF bytes.');
assert.deepEqual(manifests.baseline.matrix.map(({ name, width, height, size, theme }) => ({ name, width, height, size, theme })),
  manifests.refined.matrix.map(({ name, width, height, size, theme }) => ({ name, width, height, size, theme })),
  'Both builds must run the identical comparison matrix.');

const artifacts = [];
for (const variant of ['baseline', 'refined']) {
  for (const recording of manifests[variant].recordings) {
    const directory = path.join(root, variant, 'annotation-comparison', recording.directory);
    const frames = read(path.join(directory, 'frames.json')).frames;
    assert.ok(frames.length > 1, `${variant}/${recording.name} has actual captured frames.`);
    const lines = ['ffconcat version 1.0'];
    for (let index = 0; index < frames.length; index++) {
      // Captured frame names are generated by the recorder, never external paths.
      assert.match(frames[index].file, /^\d{5}\.png$/);
      lines.push(`file '${frames[index].file}'`);
      const duration = index + 1 < frames.length ? (frames[index + 1].timestamp - frames[index].timestamp) / 1000 : 0.5;
      lines.push(`duration ${Math.max(0.01, duration).toFixed(4)}`);
    }
    lines.push(`file '${frames.at(-1).file}'`);
    const concat = path.join(directory, 'frames.ffconcat');
    fs.writeFileSync(concat, `${lines.join('\n')}\n`);
    const gif = `${variant}-${recording.name}.gif`;
    run(['-f', 'concat', '-safe', '0', '-i', concat, '-filter_complex',
      '[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=sierra2_4a',
      '-fps_mode', 'vfr', '-loop', '0', path.join(output, gif)]);
    artifacts.push({ file: gif, variant, scenario: recording.name, kind: 'actual-captured-frames', frames: frames.length });
  }
}

const states = ['02-selection', '04-comment', '05-draft', '06-expanded', '07-source-return'];
for (const scenario of manifests.baseline.matrix) {
  for (const state of states) {
    const imageName = `${scenario.name}-${state}.png`;
    const inputs = ['baseline', 'refined'].map(variant => path.join(root, variant, 'annotation-comparison', imageName));
    if (!inputs.every(file => fs.existsSync(file))) continue;
    const result = `${scenario.name}-${state}-comparison.png`;
    run(['-i', inputs[0], '-i', inputs[1], '-filter_complex',
      "[0:v]pad=iw:ih+40:0:40:0xf5f5f5,drawtext=text='Current style':fontcolor=0x202020:fontsize=18:x=16:y=10[a];" +
      "[1:v]pad=iw:ih+40:0:40:0xf5f5f5,drawtext=text='Refined candidate':fontcolor=0x202020:fontsize=18:x=16:y=10[b];[a][b]hstack",
      '-frames:v', '1', path.join(output, result)]);
    artifacts.push({ file: result, scenario: scenario.name, state, kind: 'side-by-side-real-screenshots' });
  }
}
const observations = ['baseline', 'refined'].flatMap(variant => manifests[variant].matrix
  .filter(item => item.excerptSelection && !item.excerptSelection.selectable)
  .map(item => ({ variant, scenario: item.name, finding: 'Native drag did not select the excerpt inside the quote preview.', evidence: item.excerptSelection })));
const summary = { observations, passed: results.baseline.passed && results.refined.passed,
  boundary: 'Screenshots and GIF frames come from real Electron app captures with a synthetic local provider. Labels and side-by-side composition are added for review. No generated UI, intermediate motion, or interpolated frames.',
  sourceCommit: manifests.refined.sourceCommit, originalReferenceCommit: manifests.baseline.originalReferenceCommit,
  baselineChecks: results.baseline.checks, refinedChecks: results.refined.checks,
  matrix: manifests.baseline.matrix.map(item => item.name), artifacts };
fs.writeFileSync(path.join(output, 'comparison.json'), JSON.stringify(summary, null, 2));
const media = artifacts.map(artifact => `<figure><figcaption>${artifact.file}</figcaption><img loading="lazy" src="${artifact.file}" alt="${artifact.file}"></figure>`).join('\n');
fs.writeFileSync(path.join(output, 'index.html'), `<!doctype html><meta charset="utf-8"><title>Wuu annotation comparison</title>
<style>body{font:15px system-ui;margin:24px;background:#f7f7f7;color:#222}img{max-width:100%;height:auto}figure{margin:28px 0}figcaption{margin:8px 0;font-weight:600}</style>
<h1>Wuu annotation comparison</h1><p>${summary.boundary}</p><p>Commit: ${summary.sourceCommit}. Both full journeys passed: ${summary.passed}.</p><p>Observed limitations: ${observations.length ? observations.map(item => `${item.variant}, ${item.scenario}: ${item.finding}`).join(' ') : 'None recorded.'}</p>${media}`);
console.log(JSON.stringify({ passed: summary.passed, directory: output, artifacts: artifacts.length }, null, 2));
if (!summary.passed) process.exitCode = 1;
