#!/usr/bin/env node
/**
 * Generates the theme surface matrix (config/desktop-theme-surface-matrix.json)
 * and the theme token reference (docs/en/customize/theme-surface-matrix.md and
 * docs/zh-cn/customize/theme-surface-matrix.md) from the theme contract and the
 * host stylesheet dependency graph.
 * Run via vite-node from the desktop package:
 *
 *   cd desktop && npx vite-node ../scripts/generate-theme-surface-matrix.ts
 *
 * `--check` verifies the committed artifacts are current and exits non-zero
 * when stale (`make theme-surface-matrix-check`). This is an author/docs
 * check, not a merge gate.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  analyzeSurfaceMatrix,
  formatBaseline,
  listProductionSources,
  type SurfaceMatrix,
} from "../desktop/src/renderer/styles/themeCoverage";

const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const checkOnly = process.argv.includes("--check");

const stylesDir = resolve(repoRoot, "desktop/src/renderer/styles");
const rendererDir = resolve(repoRoot, "desktop/src/renderer");
const contractPath = resolve(repoRoot, "config/desktop-theme-contract.json");

const cssFiles = readdirSync(stylesDir)
  .filter((name) => name.endsWith(".css"))
  .sort()
  .map((name) => ({ name, source: readFileSync(resolve(stylesDir, name), "utf8") }));
const anchorSources = listProductionSources(rendererDir).map((path) => readFileSync(path, "utf8"));
const contract = JSON.parse(readFileSync(contractPath, "utf8"));

const matrix = analyzeSurfaceMatrix(cssFiles, anchorSources);
const outputs = new Map([
  [resolve(repoRoot, "config/desktop-theme-surface-matrix.json"), renderMatrixJson(matrix)],
  [
    resolve(stylesDir, "themeCoverage.baseline.txt"),
    renderCoverageBaseline(formatBaseline(cssFiles)),
  ],
  [resolve(repoRoot, "docs/en/customize/theme-surface-matrix.md"), renderDoc(matrix, contract, "en")],
  [resolve(repoRoot, "docs/zh-cn/customize/theme-surface-matrix.md"), renderDoc(matrix, contract, "zh")],
]);

let stale = false;
for (const [path, content] of outputs) {
  if (readOptional(path) === content) continue;
  stale = true;
  if (checkOnly) {
    console.error(`${relative(repoRoot, path)} is stale; run make generate-theme-surface-matrix`);
  } else {
    writeFileSync(path, content);
    console.log(`generated ${relative(repoRoot, path)}`);
  }
}

if (checkOnly && stale) process.exit(1);
if (checkOnly) console.log("theme surface matrix is current");

function renderCoverageBaseline(entries: string[]): string {
  return [
    "# Theme coverage baseline: color paint declarations whose custom-property",
    "# resolution chain does not yet reach a public --wuu-* theme token.",
    "# Generated by scripts/generate-theme-surface-matrix.ts; do not edit.",
    "",
    ...entries,
    "",
  ].join("\n");
}

function readOptional(path) {
  try {
    return readFileSync(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return undefined;
    throw error;
  }
}

/** Compact row-per-line JSON so the committed artifact stays small. */
function renderMatrixJson(matrix: SurfaceMatrix): string {
  const header = {
    schemaVersion: matrix.schemaVersion,
    generatedBy: matrix.generatedBy,
    anchors: matrix.anchors,
    tokenSet: matrix.tokenSet,
  };
  const rows = matrix.rows.map((row) => JSON.stringify(row));
  return `${JSON.stringify(header, null, 2).slice(0, -1)},\n  "rows": [\n${rows
    .map((row) => `    ${row}`)
    .join(",\n")}\n  ]\n}\n`;
}

/** Reverse view: public token -> the (anchor, state, paint property) cells it reaches. */
function tokenSurfaces(matrix: SurfaceMatrix): Map<string, string[]> {
  const cellsByToken = new Map<string, Set<string>>();
  for (const row of matrix.rows) {
    for (const token of row.tokens) {
      const cells = cellsByToken.get(token) ?? new Set<string>();
      cells.add(`${row.anchor}|${row.state}|${row.prop}`);
      cellsByToken.set(token, cells);
    }
  }
  const sorted = new Map<string, string[]>();
  for (const [token, cells] of cellsByToken) {
    sorted.set(token, [...cells].sort());
  }
  return sorted;
}

function renderDoc(matrix: SurfaceMatrix, contract, locale: "en" | "zh"): string {
  const surfaces = tokenSurfaces(matrix);
  const isWired = (token: string) => (surfaces.get(token) ?? []).length > 0;
  const zh = locale === "zh";

  const categoryLabels: Record<string, Record<string, string>> = {
    color: { zh: "颜色", en: "Color" },
    typography: { zh: "排版", en: "Typography" },
    spacing: { zh: "间距", en: "Spacing" },
    density: { zh: "密度", en: "Density" },
    radius: { zh: "圆角", en: "Radius" },
    border: { zh: "边框", en: "Border" },
    elevation: { zh: "阴影", en: "Elevation" },
    motion: { zh: "动效", en: "Motion" },
    content: { zh: "内容", en: "Content" },
  };

  const describeToken = (token) =>
    token.legacy
      ? zh
        ? `旧名称，请使用 \`${token.aliasFor}\``
        : `Legacy name; use \`${token.aliasFor}\` instead`
      : token.description?.[locale] ?? "";

  const statusText = (wired: boolean) =>
    wired
      ? zh
        ? "已接入"
        : "Wired"
      : zh
        ? "未接入（预留）"
        : "Not wired (reserved)";

  const rowsByCategory = new Map<string, string[]>();
  for (const token of contract.tokens) {
    const rows = rowsByCategory.get(token.category) ?? [];
    rows.push(`| \`${token.name}\` | ${describeToken(token)} | ${statusText(isWired(token.name))} |`);
    rowsByCategory.set(token.category, rows);
  }

  const legacyCount = contract.tokens.filter((token) => token.legacy).length;
  const wiredCount = [...contract.tokens, ...contract.syntax].filter((token) =>
    isWired(typeof token === "string" ? token : token.name),
  ).length;

  const sections = [...rowsByCategory.entries()]
    .map(
      ([category, rows]) =>
        `### ${categoryLabels[category]?.[locale] ?? category}\n\n| token | ${
          zh ? "说明" : "Description"
        } | ${zh ? "宿主" : "Host"} |\n| --- | --- | --- |\n${rows.join("\n")}`,
    )
    .join("\n\n");

  const syntaxKinds: Record<string, Record<string, string>> = {
    keyword: { zh: "关键字", en: "Keyword" },
    function: { zh: "函数名", en: "Function name" },
    string: { zh: "字符串", en: "String" },
    number: { zh: "数字", en: "Number" },
    comment: { zh: "注释", en: "Comment" },
    tag: { zh: "HTML 标签", en: "HTML tag" },
    literal: { zh: "字面量", en: "Literal" },
    meta: { zh: "元信息", en: "Meta" },
  };
  const syntaxRows = contract.syntax.map((token) => {
    const kind = token.split("-").pop() ?? token;
    const kindLabel = syntaxKinds[kind]?.[locale] ?? kind;
    return `| \`${token}\` | ${kindLabel} | ${statusText(isWired(token))} |`;
  });

  if (zh) {
    return `# 主题 Token 参考

Wuu 桌面端把界面外观收敛为一组公开的 CSS 自定义属性（design token）。插件可以通过
\`contributes.themes\` 声明主题并覆盖这些 token，也可以用 \`registerThemeTokens\`
在运行时按主题应用覆盖；机制见[插件主题](plugin-authoring.md)。

本页由 \`scripts/generate-theme-surface-matrix.ts\` 从
[\`config/desktop-theme-contract.json\`](../../../config/desktop-theme-contract.json)
与宿主样式依赖图生成（\`make generate-theme-surface-matrix\`），请勿手改；逐声明
级的覆盖明细见
[\`config/desktop-theme-surface-matrix.json\`](../../../config/desktop-theme-surface-matrix.json)。

## 覆盖方式

覆盖就是设置变量本身；宿主为每个 token 保留默认值，未覆盖的部分维持内置外观：

\`\`\`css
:root {
  --wuu-color-canvas: #f6f6f4;
  --wuu-color-text: #1c1c1a;
}
\`\`\`

## Token 一览

合同共定义 **${contract.tokens.length} 个公开 token**（其中 **${legacyCount} 个**
旧名称兼容别名）与 **${contract.syntax.length} 个语法高亮 token**；当前 **${wiredCount} 个**
已接入宿主界面。「已接入」表示宿主样式已在引用该 token，覆盖会立即生效；
「未接入（预留）」表示 token 已声明但宿主尚未引用，覆盖暂不改变任何界面。

${sections}

## 语法高亮

代码高亮颜色由 \`--wuu-syntax-*\` 控制；\`--hljs-*\` 是早期的兼容名称，两者等价。

| token | 说明 | 宿主 |
| --- | --- | --- |
${syntaxRows.join("\n")}
`;
  }

  return `# Theme token reference

Wuu Desktop derives its appearance from a set of public CSS custom properties
(design tokens). Plugins can declare themes through \`contributes.themes\` that
override these tokens, or apply overrides at runtime with \`registerThemeTokens\`;
see [plugin themes](plugin-authoring.md).

This page is generated from
[\`config/desktop-theme-contract.json\`](../../../config/desktop-theme-contract.json)
and the host stylesheet dependency graph by
\`scripts/generate-theme-surface-matrix.ts\` (run
\`make generate-theme-surface-matrix\`); do not edit it by hand. Per-declaration
coverage detail lives in
[\`config/desktop-theme-surface-matrix.json\`](../../../config/desktop-theme-surface-matrix.json).

## Overriding tokens

An override is just setting the variable; the host keeps a default for every
token, so anything you do not override keeps the built-in appearance:

\`\`\`css
:root {
  --wuu-color-canvas: #f6f6f4;
  --wuu-color-text: #1c1c1a;
}
\`\`\`

## Token list

The contract defines **${contract.tokens.length} public tokens** (**${legacyCount}**
legacy compatibility aliases) and **${contract.syntax.length} syntax-highlighting
tokens**; **${wiredCount}** of them are currently wired into host surfaces.
"Wired" means host styles already reference the token and overrides take effect;
"Not wired (reserved)" means the token is declared but the host does not consume
it yet, so overrides do not change anything.

${sections}

## Syntax highlighting

Code highlighting colors use \`--wuu-syntax-*\`; \`--hljs-*\` are the early
compatible names and both families take effect.

| token | Description | Host |
| --- | --- | --- |
${syntaxRows.join("\n")}
`;
}
