// Code generated by scripts/generate-desktop-theme-contract.mjs; DO NOT EDIT.

export const PUBLIC_THEME_TOKEN_NAMES = [
  "--wuu-paper",
  "--wuu-ink",
  "--wuu-ink-soft",
  "--wuu-hairline",
  "--wuu-surface-muted",
  "--wuu-accent",
  "--wuu-accent-press",
  "--wuu-color-canvas",
  "--wuu-color-surface",
  "--wuu-color-surface-muted",
  "--wuu-color-surface-elevated",
  "--wuu-color-overlay-backdrop",
  "--wuu-color-text",
  "--wuu-color-text-muted",
  "--wuu-color-border-subtle",
  "--wuu-color-border-strong",
  "--wuu-color-accent",
  "--wuu-color-accent-pressed",
  "--wuu-color-focus",
  "--wuu-color-success",
  "--wuu-color-warning",
  "--wuu-color-danger",
  "--wuu-color-info",
  "--wuu-color-on-accent",
  "--wuu-font-family-ui",
  "--wuu-font-family-mono",
  "--wuu-font-size-ui",
  "--wuu-font-size-body",
  "--wuu-line-height-body",
  "--wuu-space-unit",
  "--wuu-space-density",
  "--wuu-message-actions-block-gap",
  "--wuu-message-actions-overlay-gap",
  "--wuu-message-actions-control-gap",
  "--wuu-message-actions-inline-offset",
  "--wuu-message-action-size",
  "--wuu-message-action-radius",
  "--wuu-message-user-background",
  "--wuu-message-user-border",
  "--wuu-message-user-color",
  "--wuu-message-user-radius",
  "--wuu-message-user-shadow",
  "--wuu-radius-control",
  "--wuu-radius-panel",
  "--wuu-radius-overlay",
  "--wuu-border-subtle",
  "--wuu-border-strong",
  "--wuu-elevation-panel",
  "--wuu-elevation-overlay",
  "--wuu-motion-duration-fast",
  "--wuu-motion-duration-normal",
  "--wuu-motion-easing-standard",
  "--wuu-content-max-width",
] as const;

export type PublicThemeTokenName = (typeof PUBLIC_THEME_TOKEN_NAMES)[number];

export const PUBLIC_SYNTAX_TOKEN_NAMES = [
  "--hljs-keyword",
  "--hljs-function",
  "--hljs-string",
  "--hljs-number",
  "--hljs-comment",
  "--hljs-tag",
  "--hljs-literal",
  "--hljs-meta",
  "--wuu-syntax-keyword",
  "--wuu-syntax-function",
  "--wuu-syntax-string",
  "--wuu-syntax-number",
  "--wuu-syntax-comment",
  "--wuu-syntax-tag",
  "--wuu-syntax-literal",
  "--wuu-syntax-meta",
] as const;

export type PublicSyntaxTokenName = (typeof PUBLIC_SYNTAX_TOKEN_NAMES)[number];

export const LEGACY_THEME_TOKEN_ALIASES = {
  "--wuu-paper": "--wuu-color-canvas",
  "--wuu-ink": "--wuu-color-text",
  "--wuu-ink-soft": "--wuu-color-text-muted",
  "--wuu-hairline": "--wuu-color-border-subtle",
  "--wuu-surface-muted": "--wuu-color-surface-muted",
  "--wuu-accent": "--wuu-color-accent",
  "--wuu-accent-press": "--wuu-color-accent-pressed",
} as const satisfies Readonly<Partial<Record<PublicThemeTokenName, PublicThemeTokenName>>>;

const PUBLIC_THEME_TOKEN_SET: ReadonlySet<string> = new Set(PUBLIC_THEME_TOKEN_NAMES);
const PUBLIC_SYNTAX_TOKEN_SET: ReadonlySet<string> = new Set(PUBLIC_SYNTAX_TOKEN_NAMES);

export function isPublicThemeTokenName(value: string): value is PublicThemeTokenName {
  return PUBLIC_THEME_TOKEN_SET.has(value);
}

export function isPublicSyntaxTokenName(value: string): value is PublicSyntaxTokenName {
  return PUBLIC_SYNTAX_TOKEN_SET.has(value);
}

export function canonicalThemeTokenName(value: PublicThemeTokenName): PublicThemeTokenName {
  return LEGACY_THEME_TOKEN_ALIASES[value as keyof typeof LEGACY_THEME_TOKEN_ALIASES] ?? value;
}
