package insight

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateHTML writes an interactive HTML report to .wuu/insight-cache/report.html
// and returns the file path.
func GenerateHTML(workspaceRoot string, r *Report) (string, error) {
	dir := filepath.Join(workspaceRoot, ".wuu", "insight-cache")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "report.html")

	content := buildHTML(r)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func buildHTML(r *Report) string {
	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>wuu — Session Insights</title>
<style>
`)
	b.WriteString(cssStyles)
	b.WriteString(`</style>
</head>
<body>
<div class="container">
`)

	// Header.
	b.WriteString(`<header>`)
	b.WriteString(`<h1>wuu — Session Insights</h1>`)
	b.WriteString(fmt.Sprintf(`<p class="meta">Generated %s · %d sessions · %d messages · %.1f hours · %d days active</p>`,
		html.EscapeString(r.GeneratedAt.Format("2006-01-02 15:04")),
		r.Stats.TotalSessions,
		r.Stats.TotalMessages,
		r.Stats.TotalDurationH,
		r.Stats.DaysActive,
	))
	b.WriteString(`</header>`)

	// At a Glance.
	b.WriteString(`<section class="at-a-glance" id="at-a-glance">`)
	b.WriteString(`<h2>At a Glance</h2>`)
	b.WriteString(`<div class="glance-grid">`)
	writeGlanceCard(&b, "What's working", r.AtAGlance.WhatsWorking, "working")
	writeGlanceCard(&b, "What's hindering you", r.AtAGlance.WhatsHindering, "hindering")
	writeGlanceCard(&b, "Quick wins to try", r.AtAGlance.QuickWins, "wins")
	writeGlanceCard(&b, "Ambitious workflows", r.AtAGlance.AmbitiousWorkflows, "ambitious")
	b.WriteString(`</div>`)
	b.WriteString(`</section>`)

	// Stats row.
	b.WriteString(`<section class="stats-row" id="stats">`)
	writeStatCard(&b, "Messages", fmt.Sprintf("%d", r.Stats.TotalMessages))
	writeStatCard(&b, "Sessions", fmt.Sprintf("%d", r.Stats.TotalSessions))
	writeStatCard(&b, "Hours", fmt.Sprintf("%.1f", r.Stats.TotalDurationH))
	writeStatCard(&b, "Days Active", fmt.Sprintf("%d", r.Stats.DaysActive))
	writeStatCard(&b, "Msgs/Day", fmt.Sprintf("%.1f", r.Stats.MessagesPerDay))
	b.WriteString(`</section>`)

	// Charts: Tool Usage, Languages, Goals, Session Types.
	if len(r.Stats.ToolCounts) > 0 {
		writeBarChart(&b, "Top Tools", r.Stats.ToolCounts, 10, "tools")
	}
	if len(r.Stats.Languages) > 0 {
		writeBarChart(&b, "Languages", r.Stats.Languages, 10, "languages")
	}
	if len(r.Stats.GoalCategories) > 0 {
		writeBarChart(&b, "Goal Categories", r.Stats.GoalCategories, 10, "goals")
	}
	if len(r.Stats.SessionTypes) > 0 {
		writeBarChart(&b, "Session Types", r.Stats.SessionTypes, 10, "session-types")
	}
	if len(r.Stats.Outcomes) > 0 {
		writeBarChart(&b, "Outcomes", r.Stats.Outcomes, 10, "outcomes")
	}
	if len(r.Stats.Friction) > 0 {
		writeBarChart(&b, "Friction Types", r.Stats.Friction, 10, "friction")
	}

	// Time of day chart.
	if len(r.Stats.MessageHours) > 0 {
		writeTimeOfDayChart(&b, r.Stats.MessageHours)
	}

	// Navigation TOC.
	b.WriteString(`<nav class="toc" id="toc"><h2>Sections</h2><ul>`)
	b.WriteString(`<li><a href="#at-a-glance">At a Glance</a></li>`)
	b.WriteString(`<li><a href="#stats">Stats</a></li>`)
	for _, s := range r.Sections {
		id := strings.ReplaceAll(strings.ToLower(s.Name), " ", "-")
		b.WriteString(fmt.Sprintf(`<li><a href="#%s">%s</a></li>`, id, html.EscapeString(s.Title)))
	}
	b.WriteString(`</ul></nav>`)

	// Insight sections.
	for _, s := range r.Sections {
		id := strings.ReplaceAll(strings.ToLower(s.Name), " ", "-")
		b.WriteString(fmt.Sprintf(`<section id="%s">`, id))
		b.WriteString(fmt.Sprintf(`<h2>%s</h2>`, html.EscapeString(s.Title)))
		b.WriteString(`<div class="section-content">`)
		b.WriteString(markdownToHTML(s.Content))
		b.WriteString(`</div>`)
		b.WriteString(`</section>`)
	}

	// Footer.
	b.WriteString(`<footer>`)
	b.WriteString(fmt.Sprintf(`<p>Generated by <strong>wuu</strong> /insight · %s</p>`,
		html.EscapeString(r.GeneratedAt.Format("2006-01-02 15:04:05"))))
	b.WriteString(`</footer>`)

	b.WriteString(`</div>`)

	// Collapsible section JS.
	b.WriteString(`
<script>
document.querySelectorAll('.collapsible-header').forEach(h => {
  h.addEventListener('click', () => {
    const content = h.nextElementSibling;
    const arrow = h.querySelector('.arrow');
    content.classList.toggle('collapsed');
    arrow.textContent = content.classList.contains('collapsed') ? '▸' : '▾';
  });
});
</script>
`)

	b.WriteString(`</body></html>`)
	return b.String()
}

func writeGlanceCard(b *strings.Builder, title, content, cls string) {
	if content == "" {
		return
	}
	b.WriteString(fmt.Sprintf(`<div class="glance-card %s">`, cls))
	b.WriteString(fmt.Sprintf(`<h3>%s</h3>`, html.EscapeString(title)))
	b.WriteString(fmt.Sprintf(`<p>%s</p>`, html.EscapeString(content)))
	b.WriteString(`</div>`)
}

func writeStatCard(b *strings.Builder, label, value string) {
	b.WriteString(`<div class="stat-card">`)
	b.WriteString(fmt.Sprintf(`<div class="stat-value">%s</div>`, html.EscapeString(value)))
	b.WriteString(fmt.Sprintf(`<div class="stat-label">%s</div>`, html.EscapeString(label)))
	b.WriteString(`</div>`)
}

func writeBarChart(b *strings.Builder, title string, data map[string]int, maxItems int, id string) {
	type kv struct {
		k string
		v int
	}
	var items []kv
	for k, v := range data {
		items = append(items, kv{k, v})
	}
	sort.Slice(items, func(i, j int) bool { return items[i].v > items[j].v })
	if len(items) > maxItems {
		items = items[:maxItems]
	}
	if len(items) == 0 {
		return
	}
	maxVal := items[0].v

	b.WriteString(fmt.Sprintf(`<section class="chart" id="%s">`, id))
	b.WriteString(fmt.Sprintf(`<h2>%s</h2>`, html.EscapeString(title)))
	b.WriteString(`<div class="bar-chart">`)
	for _, item := range items {
		pct := 0
		if maxVal > 0 {
			pct = item.v * 100 / maxVal
		}
		if pct < 2 {
			pct = 2
		}
		b.WriteString(fmt.Sprintf(
			`<div class="bar-row"><span class="bar-label">%s</span><div class="bar-track"><div class="bar-fill" style="width:%d%%"></div></div><span class="bar-value">%d</span></div>`,
			html.EscapeString(item.k), pct, item.v,
		))
	}
	b.WriteString(`</div></section>`)
}

func writeTimeOfDayChart(b *strings.Builder, hours []int) {
	counts := make([]int, 24)
	maxCount := 0
	for _, h := range hours {
		if h >= 0 && h < 24 {
			counts[h]++
			if counts[h] > maxCount {
				maxCount = counts[h]
			}
		}
	}

	b.WriteString(`<section class="chart" id="time-of-day">`)
	b.WriteString(`<h2>Time of Day</h2>`)
	b.WriteString(`<div class="tod-chart">`)
	for h := 0; h < 24; h++ {
		pct := 0
		if maxCount > 0 {
			pct = counts[h] * 100 / maxCount
		}
		label := fmt.Sprintf("%02d", h)
		b.WriteString(fmt.Sprintf(
			`<div class="tod-bar"><div class="tod-fill" style="height:%d%%"></div><span class="tod-label">%s</span></div>`,
			pct, label,
		))
	}
	b.WriteString(`</div></section>`)
}

// markdownToHTML does a basic markdown-to-HTML conversion for section content.
// Handles: headers, bold, italic, lists, paragraphs.
func markdownToHTML(md string) string {
	var b strings.Builder
	lines := strings.Split(md, "\n")
	inList := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if trimmed == "" {
			if inList {
				b.WriteString("</ul>\n")
				inList = false
			}
			continue
		}

		// Headers.
		if strings.HasPrefix(trimmed, "### ") {
			if inList {
				b.WriteString("</ul>\n")
				inList = false
			}
			b.WriteString("<h4>" + inlineFormat(html.EscapeString(trimmed[4:])) + "</h4>\n")
			continue
		}
		if strings.HasPrefix(trimmed, "## ") {
			if inList {
				b.WriteString("</ul>\n")
				inList = false
			}
			b.WriteString("<h3>" + inlineFormat(html.EscapeString(trimmed[3:])) + "</h3>\n")
			continue
		}

		// List items.
		if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			if !inList {
				b.WriteString("<ul>\n")
				inList = true
			}
			b.WriteString("<li>" + inlineFormat(html.EscapeString(trimmed[2:])) + "</li>\n")
			continue
		}
		// Numbered list.
		if len(trimmed) > 2 && trimmed[0] >= '0' && trimmed[0] <= '9' && (trimmed[1] == '.' || (len(trimmed) > 2 && trimmed[2] == '.')) {
			if !inList {
				b.WriteString("<ul>\n")
				inList = true
			}
			idx := strings.Index(trimmed, ". ")
			if idx > 0 {
				b.WriteString("<li>" + inlineFormat(html.EscapeString(trimmed[idx+2:])) + "</li>\n")
				continue
			}
		}

		// Paragraph.
		if inList {
			b.WriteString("</ul>\n")
			inList = false
		}
		b.WriteString("<p>" + inlineFormat(html.EscapeString(trimmed)) + "</p>\n")
	}
	if inList {
		b.WriteString("</ul>\n")
	}
	return b.String()
}

// inlineFormat handles **bold** and _italic_ in already-escaped HTML.
func inlineFormat(s string) string {
	// Bold: **text**
	for {
		start := strings.Index(s, "**")
		if start < 0 {
			break
		}
		end := strings.Index(s[start+2:], "**")
		if end < 0 {
			break
		}
		end += start + 2
		s = s[:start] + "<strong>" + s[start+2:end] + "</strong>" + s[end+2:]
	}
	// Italic: _text_ (but not inside words)
	for {
		start := strings.Index(s, "_")
		if start < 0 {
			break
		}
		end := strings.Index(s[start+1:], "_")
		if end < 0 {
			break
		}
		end += start + 1
		s = s[:start] + "<em>" + s[start+1:end] + "</em>" + s[end+1:]
	}
	return s
}

const cssStyles = `
:root {
  --brand: #D77757;
  --brand-light: #EB9F7F;
  --bg: #1a1b1e;
  --bg-card: #23252a;
  --bg-hover: #2a2d33;
  --text: #e0e0e0;
  --text-dim: #888;
  --border: #333;
  --success: #4eba65;
  --error: #ff6b80;
  --warning: #ffc107;
  --blue: #61afef;
  --purple: #b1b9f9;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem;
}

.container { max-width: 900px; margin: 0 auto; }

header { margin-bottom: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 1rem; }
header h1 { color: var(--brand); font-size: 1.8rem; }
header .meta { color: var(--text-dim); font-size: 0.9rem; margin-top: 0.3rem; }

h2 { color: var(--brand); margin: 1.5rem 0 0.8rem; font-size: 1.3rem; }
h3 { color: var(--brand-light); margin: 1rem 0 0.5rem; font-size: 1.1rem; }
h4 { color: var(--text); margin: 0.8rem 0 0.4rem; font-size: 1rem; }

p { margin-bottom: 0.6rem; }
ul { margin: 0.4rem 0 0.8rem 1.5rem; }
li { margin-bottom: 0.3rem; }
strong { color: var(--brand-light); }

section { margin-bottom: 1.5rem; }

.section-content {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem 1.2rem;
}

/* At a Glance */
.glance-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}
.glance-card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  border-left: 3px solid var(--brand);
}
.glance-card.working { border-left-color: var(--success); }
.glance-card.hindering { border-left-color: var(--error); }
.glance-card.wins { border-left-color: var(--blue); }
.glance-card.ambitious { border-left-color: var(--purple); }
.glance-card h3 { font-size: 0.9rem; color: var(--text-dim); margin-bottom: 0.3rem; }
.glance-card p { font-size: 0.95rem; }

/* Stats Row */
.stats-row {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
  margin: 1.5rem 0;
}
.stat-card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0.8rem 1.2rem;
  text-align: center;
  flex: 1;
  min-width: 100px;
}
.stat-value { font-size: 1.4rem; font-weight: bold; color: var(--brand); }
.stat-label { font-size: 0.8rem; color: var(--text-dim); margin-top: 0.2rem; }

/* Bar Charts */
.bar-chart { margin: 0.5rem 0; }
.bar-row {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.4rem;
}
.bar-label {
  width: 140px;
  text-align: right;
  font-size: 0.85rem;
  color: var(--text-dim);
  flex-shrink: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.bar-track {
  flex: 1;
  height: 20px;
  background: var(--bg-card);
  border-radius: 4px;
  overflow: hidden;
}
.bar-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--brand), var(--brand-light));
  border-radius: 4px;
  transition: width 0.3s ease;
}
.bar-value {
  width: 40px;
  font-size: 0.85rem;
  color: var(--text-dim);
  text-align: right;
}

/* Time of Day Chart */
.tod-chart {
  display: flex;
  align-items: flex-end;
  gap: 2px;
  height: 120px;
  margin: 0.5rem 0;
  padding: 0.5rem;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 8px;
}
.tod-bar {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: flex-end;
  height: 100%;
}
.tod-fill {
  width: 100%;
  background: linear-gradient(0deg, var(--brand), var(--brand-light));
  border-radius: 2px 2px 0 0;
  min-height: 2px;
}
.tod-label {
  font-size: 0.65rem;
  color: var(--text-dim);
  margin-top: 4px;
}

/* TOC */
.toc {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  margin: 1.5rem 0;
}
.toc ul { list-style: none; margin: 0; padding: 0; display: flex; flex-wrap: wrap; gap: 0.5rem; }
.toc li a {
  color: var(--brand);
  text-decoration: none;
  padding: 0.3rem 0.6rem;
  border-radius: 4px;
  font-size: 0.85rem;
  background: var(--bg-hover);
}
.toc li a:hover { background: var(--brand); color: var(--bg); }

footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  color: var(--text-dim);
  font-size: 0.85rem;
  text-align: center;
}

@media (max-width: 600px) {
  body { padding: 1rem; }
  .glance-grid { grid-template-columns: 1fr; }
  .stats-row { flex-direction: column; }
  .bar-label { width: 80px; }
}
`
